GET http://localhost:10000

###

GET http://localhost:10000/api/get/cards

###

GET http://localhost:10000/api/my/cards

###

GET http://localhost:10000/api/my/card/33333

###

POST http://localhost:10000/api/card/0
Content-Type: application/json

{
  "client_id": 1,
  "pin": 4444,
  "balance": 999999,
  "cvv": 333,
  "holder_name": "TESTHOLDERNAME",
  "validity": "1222"
}

###

POST http://localhost:10000/api/card/lock
Content-Type: application/json

{
  "pan": 33333
}

###

POST http://localhost:10000/api/card/unlock
Content-Type: application/json

{
  "pan": 11111
}

###

POST http://localhost:10000/api/my/card/1/lock

###

POST http://localhost:10000/api/my/card/1/unlock

###